### PR TITLE
OMP port

### PR DESCRIPTION
**Pull request by defstat**

### CODE REVIEW

**Comment by ajnyga** [comment]
Thanks! Bozana did a lot of changes to the plugin, so I will merge those first and then probably hand pick your changes from this pr. I will let you know when I am done if you can test it with OMP.

**Comment by ajnyga** [comment]
Hi @defstat, I added your changes to this branch: https://github.com/ajnyga/funding/tree/omp-port
Could you test that with OMP? I combined `addArticleDisplay `and `addMonographDisplay` into `addSubmissionDisplay`.  Note that the plugin name has changed, but the database table should be the same as before.

@bozana can check this out as well if you have time.

**Comment by bozana** [comment]
@ajnyga, I tested it and it works well... :-) THANKS!

**Comment by ajnyga** [comment]
fyi @defstat and @bozana master branch should now include the omp-port changes...

**Pull request closed without merging**
