### PR TITLE
consider funders in Crossref XML export, plugin rename, and some code cleaning

### PR DESCRIPTION
**Pull request by bozana**

### CODE REVIEW

**Comment by ajnyga** [comment]
Wow, you have been busy :D I will test and merge these later today. 

If I understood correctly, there is now a new hook in the CrossRef plugin which this plugin is triggering? Are you planning to have similar hooks in other export plugins as well?

**Comment by bozana** [comment]
Yes, there is a new filter hook for export plugins. I.e. the same kind of hook can be used for DataCite too, for OpenAIRE another one can be used...

**Comment by bozana** [comment]
@ajnyga, I also renamed the plugin (s. the last commit). Then you could rename the whole repository too... THANKS!!!

**Comment by ajnyga** [comment]
Thanks @bozana I tested this a while ago and seemd to work very well! 

After the OMP port is ok, I will merge those changes to the master branch and see what is still missing. At least OAI-PMH.

**Pull request merged**
